FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine
COPY bin/Debug/net5.0 App/
WORKDIR /App

RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

ENTRYPOINT [ "dotnet", "ElsaPlayground.dll"]