version: "3"
services:
  rabbit1:
    image: rabbitmq:3.9-management
    hostname: rabbit1
    ports:
     - "4369:4369"
     - "5672:5672"
     - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-admin}
  rabbit2:
    image: rabbitmq:3.9-management
    hostname: rabbit2
    links:
      - rabbit1
    ports:
     - "4370:4369"
     - "5673:5672"
     - "15673:15672"
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit1
      - RAM_NODE=true
  rabbit3:
    image: rabbitmq:3.9-management
    hostname: rabbit3
    links:
      - rabbit1
      - rabbit2
    ports:
     - "4371:4369"
     - "5674:5672"
     - "15674:15672"
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit1